package com.myfirstproject;

import com.myfirstproject.utilities.TestBase;
import org.junit.Assert;
import org.junit.Test;
import org.openqa.selenium.Alert;
import org.openqa.selenium.By;

public class Day06_Alerts extends TestBase {
    /*
    Go to https://testcenter.techproeducation.com/index.php?page=javascript-alerts
Create a class: AlertTest
Create setUp method
Create 3 test methods:
acceptAlert() =>
dismissAlert()==>
sendKeysAlert()=>
     */

    /*
  What is alert?
  -it is a pop up that is generated by JS
  -alerts are used to give informational messages
  -when there is an alert pop up on the page, we must handle the alert otherwise we cannot move on
  How do you handle alerts?
  -switch to alert then use
  accept to click OK,
  dismiss to click Cancel,
  getText to get the text,
  and sendKeys to type on the alert
   */
    @Test
    public void acceptAlert(){
/*
acceptAlert() => click on the first alert,
verify the text “I am a JS Alert” ,
click OK ,
and Verify “You successfully clicked an alert”
 */
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        driver.findElement(By.xpath("//button[@onclick='jsAlert()']")).click();
        String acceptAlerttext=driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS Alert",acceptAlerttext);
        driver.switchTo().alert().accept();
        String acceptText=driver.findElement(By.id("result")).getText();
Assert.assertEquals("You successfully clicked an alert",acceptText);
    }
    @Test
    public void dismissAlert(){
/*
dismissAlert()=> click on the second alert,
verify text "I am a JS Confirm”,
click cancel,
and Verify “You clicked: Cancel”
 */
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        driver.findElement(By.xpath("//button[@onclick='jsConfirm()']")).click();
        String dismissAlerttext=driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS Confirm",dismissAlerttext);
        driver.switchTo().alert().dismiss();
        String dismissText=driver.findElement(By.id("result")).getText();
        Assert.assertEquals("You clicked: Cancel",dismissText);
    }
    @Test
    public void sendKeysAlert(){

/*
sendKeysAlert()=> click on the third alert,
verify text “I am a JS prompt”,
type “Hello World”,
click OK,
and Verify “You entered: Hello World”
Collapse
 */
        driver.get("https://testcenter.techproeducation.com/index.php?page=javascript-alerts");
        driver.findElement(By.xpath("//button[@onclick='jsPrompt()']")).click();
        String actualALertText=driver.switchTo().alert().getText();
        Assert.assertEquals("I am a JS prompt",actualALertText);
        driver.switchTo().alert().sendKeys("Hello World");
        driver.switchTo().alert().accept();
        String text=driver.findElement(By.id("result")).getText();
        Assert.assertEquals("You entered: Hello World",text);
    }


}
